# Learn more about Streamlit secrets!
# docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management#develop-locally-with-secrets
{% if cookiecutter.app_uses_snowflake %}
[snowflake]
    user = "..."
    account = "..."
    password = "..."
    warehouse = "..."
{% endif %}